spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Descatles/spring-boot-secure-communications-using-end-to-end-tls-ssl-config.git
          default-label: wenhao/tls
        native:
          search-locations: classpath:.
  profiles:
    active: native
