spring:
  application:
    name: gateway
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}

azure:
  keyvault:
    uri: ${KEY_VAULT_URI}
    jca:
      overrideTrustManagerFactory: true
      disableHostnameVerification: true

server:
  ssl:
    enabled: true
    key-alias: ${SERVER_SSL_CERTIFICATE_NAME}
    key-store-type: AzureKeyVault

---

spring:
  profiles: development
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user